pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'add--yours', url: 'https://github.com/bhavinparekh/Amazon_category_scrapping.git']]])
            }
        }
        stage('Build') {
            steps {
                git credentialsId: 'add--yours', url: 'https://github.com/bhavinparekh/Amazon_category_scrapping.git'
                sh 'docker-compse up --build'
            }
        }
        stage('Test') {
            steps {
                echo 'Job Done and Tested'
            }
        }
    }
}
docker run --name jenkins-blueocean --rm --detach   --network jenkins --env DOCKER_HOST=tcp://docker:2376   --env DOCKER_CERT_PATH=/certs/client --env DOCKER_TLS_VERIFY=1   --publish 8080:8080 --publish 50000:50000   --volume jenkins-data:/var/jenkins_home   --volume jenkins-docker-certs:/certs/client:ro   myjenkins-blueocean:1.1
